### ISSUE TITLE
Remove Provider Configuration

### ISSUE THREAD

**Issue by agosto-lorinronken** [kumarvna/terraform-azurerm-vm-scale-sets#10]
Please refer to the issue [here](https://github.com/kumarvna/terraform-azurerm-mssql-db/issues/8) as well.

We are encountering issues when sourcing this public module in our deployment as there is a provider configuration defined in the versions.tf file. With Terraform v0.13 it is recommended to remove provider blocks from your module definitions. Please refer to the following document below for more information:

https://www.terraform.io/docs/language/modules/develop/providers.html#legacy-shared-modules-with-provider-configurations

**Comment by kumarvna** [comment]
Hi,
This issue is corrected, and the module now supports the meta arguments includes providers, depends_on, count, and for_each. Please, use the latest release and revert if any problems still.
